---
name: release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: test
        run: xcodebuild test -project Notation.xcodeproj -scheme NotationTests
      - name: build nvalt
        run: |
          xcodebuild \
            -target Notation \
            -configuration ForBuilding \
            -scheme 'Notation Release' \
            -archivePath ./nvalt.xcarchive \
            archive
          ditto -c -k --keepParent nvalt.xcarchive/Products/Applications/nvALT.app nvALT.zip
      - uses: actions/upload-artifact@v7
        with:
          name: nvALT
          path: nvALT.zip
      - name: release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            nvALT.zip
